### ISSUE TITLE
feat: 소켓 서버 개발 

### ISSUE THREAD

**Issue by dev1week** [dev1week/docs#3]
## Description ✏
- Issue에 대해 설명해주세요.

## Todo 📝
- [x] mongoDB 연결 
- [x] 소켓서버 생성 
- [x] 최초 사용자 진입시 아이디 부여 로직 작성 
- [x] 각 문서마다 정보를 다르게 관리하기 위해 documentId에 맞는 방을 생성 
- [x] 퍼블리싱을 이용해 현재 문서의 내용과 접속되어있는 사용자 정보를 전송 
- [x] 현재 작성중인 글 저장 로직 
- [x] 실시간으로 작성된 글을 전체 유저에게 pub 
- [x] 문서 유무 확인 로직 작성 

## ETC 📌
- 남길 말을 적어주세요.
