### ISSUE TITLE
chore: 클라이언트 기본 설정 및 소켓 연결 

### ISSUE THREAD

**Issue by dev1week** [dev1week/docs#5]
## Description ✏
- Issue에 대해 설명해주세요.

## Todo 📝
- [x] 라이브러리 종속성 설치 
- [x] CRACO 라이브러리 설정 
- [x] 소켓 연결을 위한 socket.js  작성

## ETC 📌
- 남길 말을 적어주세요.
